### ISSUE TITLE
Facing an exception in stateful service constructor in sample code  System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by Vikhyat08** [SoCreate/service-fabric-distributed-cache#11]
System.IO.FileNotFoundException: 'Could not load file or assembly 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\NS_7\Microsoft.ServiceFabric.Data.Impl.dll'. The system cannot find the path specified.'

Getting this exception in sample project and when i try to SOCreate distributed cache store in my project.

**Comment by lurock** [comment]
Are you running the 7.x version of Service Fabric?  The most recent version of the cache is compiled to run on the 7.x version of Service Fabric.

**Comment by Vikhyat08** [comment]
@lurock Thanks for the prompt reply. 
I was running old SDK. Updated it from [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started) and the solution works now.
