### ISSUE TITLE
Support configure FabricTransportRemotingListenerSettings for authentication

### ISSUE THREAD

**Issue by qinxgit** [SoCreate/service-fabric-distributed-cache#28]
Can it be added support to allow change settings of FabricTransportRemotingListenerSettings when the cache service is starting up, so that SecurityCredentials of this setting can be set accordingly to do a authenticated communication between cache client and cache service?

This is pretty important for serious applications to avoid unwanted client to talk to the cache service.

**Comment by JustinCouto** [comment]
Hi @qinxgit 

This is something we would be happy to take a pull request for.  We are not currently adding features to this project as its current state is doing what we need it to.  If you need this in your project, please submit a pull request.

**Comment by qinxgit** [comment]
@JustinCouto  

Thanks. Fortunately, I found out that no code change is needed. Just put this into both client and service side's Config/Settings.xml file will enable the certificate based authentication. It will be parsed by the runtime in the backend.
```xml
<Section Name="TransportSettings">
    <Parameter Name="SecurityCredentialsType" Value="X509" />
    <Parameter Name="CertificateFindType" Value="FindBySubjectName" />
    <Parameter Name="CertificateFindValue" Value="test.company.com" />
    <Parameter Name="CertificateStoreLocation" Value="LocalMachine" />
    <Parameter Name="CertificateStoreName" Value="My" />
    <Parameter Name="CertificateProtectionLevel" Value="EncryptAndSign" />
    <Parameter Name="CertificateRemoteCommonNames" Value="test.company.com" />
  </Section>
```

**Comment by JustinCouto** [comment]
Great!
