### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by dmytro-gokun** [SoCreate/service-fabric-distributed-cache#3]
Hi,

is there any way to monitor the current cache size, number of entries in cache, reads/sec, writes/sec and so on? Ideally, via Azure Monitor metrics.

Thanks

**Comment by lurock** [comment]
Not currently.  That would be a great improvement.  If you are interested in adding that via a PR that would be awesome.

**Comment by dmytro-gokun** [comment]
@lurock Thank you for information! At the moment we decided to go with https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.sqlserver.sqlservercache?view=aspnetcore-2.2 + custom metrics, as it was the easiest possible solution for our task.
