### ISSUE TITLE
unexplained cache failure after some time

### ISSUE THREAD

**Issue by larlew** [SoCreate/service-fabric-distributed-cache#34]
Is there a potential memory leak?

![image](https://github.com/SoCreate/service-fabric-distributed-cache/assets/31042542/afdf24ba-43fd-47bb-83a6-9a8cba5f0c71)

**Comment by JustinCouto** [comment]
Hello,

We had not seen this in our use.  That doesn't mean it is not an issues.  If you find the issue and submit a pull request, we will review it and add your contribution if it all looks good.
