### ISSUE TITLE
Service Fabric Depenencies locked to specific patch versions

### ISSUE THREAD

**Issue by Ryanman** [SoCreate/service-fabric-distributed-cache#9]
Hi all.

I'l create a PR for this if necessary, but right now package references are locked to specific **patch** version numbers. Can these not be 4.0.X?

You can imagine this creates an un necessary NuGet nightmare when using this cache package. Any chance of getting this updated?

Thanks!

**Comment by lurock** [comment]
Submit a PR with the tests passing add I can get it in.

**Comment by Ryanman** [comment]
Thanks man!
